package com.hallth.domain;

public class OaDataTypeDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_id
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_code
     *
     * @mbggenerated
     */
    private Integer typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_value
     *
     * @mbggenerated
     */
    private String typeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_desc
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_data_type_dic.type_parent
     *
     * @mbggenerated
     */
    private String typeParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_id
     *
     * @return the value of oa_data_type_dic.type_id
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_id
     *
     * @param typeId the value for oa_data_type_dic.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_name
     *
     * @return the value of oa_data_type_dic.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_name
     *
     * @param typeName the value for oa_data_type_dic.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_code
     *
     * @return the value of oa_data_type_dic.type_code
     *
     * @mbggenerated
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_code
     *
     * @param typeCode the value for oa_data_type_dic.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_value
     *
     * @return the value of oa_data_type_dic.type_value
     *
     * @mbggenerated
     */
    public String getTypeValue() {
        return typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_value
     *
     * @param typeValue the value for oa_data_type_dic.type_value
     *
     * @mbggenerated
     */
    public void setTypeValue(String typeValue) {
        this.typeValue = typeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_desc
     *
     * @return the value of oa_data_type_dic.type_desc
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_desc
     *
     * @param typeDesc the value for oa_data_type_dic.type_desc
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_data_type_dic.type_parent
     *
     * @return the value of oa_data_type_dic.type_parent
     *
     * @mbggenerated
     */
    public String getTypeParent() {
        return typeParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_data_type_dic.type_parent
     *
     * @param typeParent the value for oa_data_type_dic.type_parent
     *
     * @mbggenerated
     */
    public void setTypeParent(String typeParent) {
        this.typeParent = typeParent;
    }

    public JSONBean toJsonBean(){
        JSONBean jsonBean = new JSONBean();
        jsonBean.setId(this.typeCode + "");
        jsonBean.setText(this.typeValue);
        return jsonBean;
    }
}