package com.hallth.domain;

import java.util.Date;

public class OaLeaveInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_id
     *
     * @mbggenerated
     */
    private String leaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_start_time
     *
     * @mbggenerated
     */
    private Date leaveStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_end_time
     *
     * @mbggenerated
     */
    private Date leaveEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_day_count
     *
     * @mbggenerated
     */
    private Float leaveDayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_status
     *
     * @mbggenerated
     */
    private String leaveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_type
     *
     * @mbggenerated
     */
    private Integer leaveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_leave_info.leave_desc
     *
     * @mbggenerated
     */
    private String leaveDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_id
     *
     * @return the value of oa_leave_info.leave_id
     *
     * @mbggenerated
     */
    public String getLeaveId() {
        return leaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_id
     *
     * @param leaveId the value for oa_leave_info.leave_id
     *
     * @mbggenerated
     */
    public void setLeaveId(String leaveId) {
        this.leaveId = leaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.create_user
     *
     * @return the value of oa_leave_info.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.create_user
     *
     * @param createUser the value for oa_leave_info.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.create_time
     *
     * @return the value of oa_leave_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.create_time
     *
     * @param createTime the value for oa_leave_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_start_time
     *
     * @return the value of oa_leave_info.leave_start_time
     *
     * @mbggenerated
     */
    public Date getLeaveStartTime() {
        return leaveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_start_time
     *
     * @param leaveStartTime the value for oa_leave_info.leave_start_time
     *
     * @mbggenerated
     */
    public void setLeaveStartTime(Date leaveStartTime) {
        this.leaveStartTime = leaveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_end_time
     *
     * @return the value of oa_leave_info.leave_end_time
     *
     * @mbggenerated
     */
    public Date getLeaveEndTime() {
        return leaveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_end_time
     *
     * @param leaveEndTime the value for oa_leave_info.leave_end_time
     *
     * @mbggenerated
     */
    public void setLeaveEndTime(Date leaveEndTime) {
        this.leaveEndTime = leaveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_day_count
     *
     * @return the value of oa_leave_info.leave_day_count
     *
     * @mbggenerated
     */
    public Float getLeaveDayCount() {
        return leaveDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_day_count
     *
     * @param leaveDayCount the value for oa_leave_info.leave_day_count
     *
     * @mbggenerated
     */
    public void setLeaveDayCount(Float leaveDayCount) {
        this.leaveDayCount = leaveDayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_status
     *
     * @return the value of oa_leave_info.leave_status
     *
     * @mbggenerated
     */
    public String getLeaveStatus() {
        return leaveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_status
     *
     * @param leaveStatus the value for oa_leave_info.leave_status
     *
     * @mbggenerated
     */
    public void setLeaveStatus(String leaveStatus) {
        this.leaveStatus = leaveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_type
     *
     * @return the value of oa_leave_info.leave_type
     *
     * @mbggenerated
     */
    public Integer getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_type
     *
     * @param leaveType the value for oa_leave_info.leave_type
     *
     * @mbggenerated
     */
    public void setLeaveType(Integer leaveType) {
        this.leaveType = leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_leave_info.leave_desc
     *
     * @return the value of oa_leave_info.leave_desc
     *
     * @mbggenerated
     */
    public String getLeaveDesc() {
        return leaveDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_leave_info.leave_desc
     *
     * @param leaveDesc the value for oa_leave_info.leave_desc
     *
     * @mbggenerated
     */
    public void setLeaveDesc(String leaveDesc) {
        this.leaveDesc = leaveDesc;
    }
}