package com.hallth.domain;

public class OaMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_path
     *
     * @mbggenerated
     */
    private String menuPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu.menu_icon
     *
     * @mbggenerated
     */
    private String menuIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_id
     *
     * @return the value of oa_menu.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_id
     *
     * @param menuId the value for oa_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_path
     *
     * @return the value of oa_menu.menu_path
     *
     * @mbggenerated
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_path
     *
     * @param menuPath the value for oa_menu.menu_path
     *
     * @mbggenerated
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_name
     *
     * @return the value of oa_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_name
     *
     * @param menuName the value for oa_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.parent_id
     *
     * @return the value of oa_menu.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.parent_id
     *
     * @param parentId the value for oa_menu.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu.menu_icon
     *
     * @return the value of oa_menu.menu_icon
     *
     * @mbggenerated
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu.menu_icon
     *
     * @param menuIcon the value for oa_menu.menu_icon
     *
     * @mbggenerated
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }
}