package com.hallth.domain;

public class OaMenuUserRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu_user_rel.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_menu_user_rel.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu_user_rel.user_id
     *
     * @return the value of oa_menu_user_rel.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu_user_rel.user_id
     *
     * @param userId the value for oa_menu_user_rel.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_menu_user_rel.menu_id
     *
     * @return the value of oa_menu_user_rel.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_menu_user_rel.menu_id
     *
     * @param menuId the value for oa_menu_user_rel.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}