package com.hallth.domain;

public class OaSeq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_seq.seq_name
     *
     * @mbggenerated
     */
    private String seqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_seq.next_id
     *
     * @mbggenerated
     */
    private Integer nextId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_seq.seq_name
     *
     * @return the value of oa_seq.seq_name
     *
     * @mbggenerated
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_seq.seq_name
     *
     * @param seqName the value for oa_seq.seq_name
     *
     * @mbggenerated
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_seq.next_id
     *
     * @return the value of oa_seq.next_id
     *
     * @mbggenerated
     */
    public Integer getNextId() {
        return nextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_seq.next_id
     *
     * @param nextId the value for oa_seq.next_id
     *
     * @mbggenerated
     */
    public void setNextId(Integer nextId) {
        this.nextId = nextId;
    }

    public OaSeq(Integer nextId, String seqName) {
        this.seqName = seqName;
        this.nextId = nextId;
    }
}