package com.hallth.mapper;

import com.hallth.domain.OaEduHis;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface OaEduHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    int insert(OaEduHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    int insertSelective(OaEduHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    OaEduHis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaEduHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_edu_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaEduHis record);

    List<OaEduHis> getEduHisInfoByUserId(OaEduHis param);

    int getEduHisInfoByUserIdCount(OaEduHis param);
}