package com.hallth.mapper;

import com.hallth.domain.OaLeaveInfo;

public interface OaLeaveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    int insert(OaLeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    int insertSelective(OaLeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    OaLeaveInfo selectByPrimaryKey(String leaveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaLeaveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_leave_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaLeaveInfo record);
}