package com.hallth.mapper;

import com.hallth.domain.OaMenuUserRel;

import java.util.List;

public interface OaMenuUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_menu_user_rel
     *
     * @mbggenerated
     */
    int insert(OaMenuUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_menu_user_rel
     *
     * @mbggenerated
     */
    int insertSelective(OaMenuUserRel record);

    List<OaMenuUserRel> getMenuIdByUserId(OaMenuUserRel rel);
}