package com.hallth.mapper;

import com.hallth.domain.OaSeq;
import org.springframework.web.bind.annotation.RequestParam;

public interface OaSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_seq
     *
     * @mbggenerated
     */
    int insert(OaSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_seq
     *
     * @mbggenerated
     */
    int insertSelective(OaSeq record);

    int getNextId(@RequestParam("seqName") String seqName);

    int updateSeq(OaSeq record);
}